### ISSUE TITLE
POS tags

### ISSUE THREAD

**Issue by souravmpi** [RenShuhuai-Andy/POS-Tagging#1]
Hi,
Thanks a lot for your work. Would it be possible to get the labels for the different PoS labels?
For example, nt -> Temporal Noun

Regards,
Sourav

**Comment by RenShuhuai-Andy** [comment]
Hi, sorry for the late reply. 

I'm sorry that I don't have the labels for the different POS labels, but you can check this link [https://www.biaodianfu.com/pos-tagging-set.html](https://www.biaodianfu.com/pos-tagging-set.html). Hope that would be helpful.

**Comment by souravmpi** [comment]
Hi, 
Thanks a lot for the link and the reference. This is indeed great!! :)
Regards,
Sourav
